version: '3'
services:
  frontend:
    build:
      context: ./frontend
      args:
        BASE_URL: "http://backend:8000"
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: "mongodb://mongodb:27017"
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
